<Workspace Version="1.0.0.1180" X="247.793930147835" Y="128.886544296484" zoom="0.443809048969359" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <CoreNodeModels.Input.DirectoryObject guid="b04e7ba6-1707-4d71-b1ad-02bb4a7e325f" type="CoreNodeModels.Input.DirectoryObject" nickname="Directory.FromPath" x="200.505407942348" y="515.282285454182" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" />
    <CoreNodeModels.Input.Directory guid="cfce217e-eec0-4cc4-986f-e436fcbb5fe6" type="CoreNodeModels.Input.Directory" nickname="Directory Path" x="-241.038619948662" y="506.61983052553" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.String>C:\Users\nvo\OneDrive - Arkitekterne M.A.A.Schmidt\Desktop\Reloade</System.String>
      <HintPath>C:\Users\nvo\OneDrive - Arkitekterne M.A.A.Schmidt\Desktop\Reloade</HintPath>
    </CoreNodeModels.Input.Directory>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="e7c0e353-0c80-4079-b6da-9f71bcd11cfc" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Directory.Contents" x="299.302963201122" y="717.410804076368" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="DSCoreNodes.dll" function="DSCore.IO.Directory.Contents@System.IO.DirectoryInfo,string">
      <PortInfo index="1" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="d379fe5f-0813-44ba-92c8-ab0d82d6b885" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="44.2112937965735" y="779.267318995386" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="&quot;parkeringspace.rvt&quot;;" ShouldFocus="false" />
    <CoreNodeModels.Watch guid="7df493e4-2369-49c5-b5ad-e240ed37df01" type="CoreNodeModels.Watch" nickname="Watch" x="587.300421964762" y="715.640871262479" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" />
    <PythonNodeModels.PythonNode guid="fd5581a1-ffe1-4532-b7f6-5f97b2634a7b" type="PythonNodeModels.PythonNode" nickname="Python Script" x="857.679093977377" y="740.313525648805" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <Script>#python nodes in dynamo 1.0.0
#proposed by Nicklas Ã˜stertgaard  nvo@bimshark.com

import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
# Import ToDSType(bool) extension method
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
# Import geometry conversion extension methods
clr.ImportExtensions(Revit.GeometryConversion)
# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
from System.Collections.Generic import *
# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application
uidoc=DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument

# Start Transaction
TransactionManager.Instance.EnsureInTransaction(doc)

# Create the Revit Link Type
# creae a for loop
#mp = ModelPathUtils.ConvertUserVisiblePathToModelPath(UnwrapElement(IN[1]))
mp = ModelPathUtils.ConvertUserVisiblePathToModelPath("C:\Dynamo\parkeringspace.rvt")
lnkOp = RevitLinkOptions("")
loadedLnkType = RevitLinkType.Create(doc, mp, lnkOp)
 
# Create the Revit Link Instance
lnkInstance = RevitLinkInstance.Create(doc, loadedLnkType.ElementId)

# End Transaction
TransactionManager.Instance.TransactionTaskDone()

OUT="Worked"</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="b04e7ba6-1707-4d71-b1ad-02bb4a7e325f" start_index="0" end="e7c0e353-0c80-4079-b6da-9f71bcd11cfc" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="cfce217e-eec0-4cc4-986f-e436fcbb5fe6" start_index="0" end="b04e7ba6-1707-4d71-b1ad-02bb4a7e325f" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e7c0e353-0c80-4079-b6da-9f71bcd11cfc" start_index="0" end="7df493e4-2369-49c5-b5ad-e240ed37df01" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d379fe5f-0813-44ba-92c8-ab0d82d6b885" start_index="0" end="e7c0e353-0c80-4079-b6da-9f71bcd11cfc" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7df493e4-2369-49c5-b5ad-e240ed37df01" start_index="0" end="fd5581a1-ffe1-4532-b7f6-5f97b2634a7b" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>